#!/bin/bash

# Pastikan script dijalankan sebagai root
if [ "$EUID" -ne 0 ]
  then echo "Silakan jalankan script ini sebagai root"
  exit
fi

# Membuat user baru dengan nama "newuser" dan password "newpassword"
read -p "Masukkan nama user baru: " newuser
useradd -m -p $(openssl passwd -1 newpassword) $newuser

# Menambahkan user baru ke grup sudo (hanya untuk Debian)
usermod -aG sudo $newuser

# Menambahkan user baru ke grup sudo (hanya untuk Ubuntu)
usermod -aG sudo $newuser

echo "User baru telah berhasil dibuat"


# Buat salinan cadangan dari file konfigurasi SSH
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

# Ubah pengaturan pada file konfigurasi SSH untuk mengizinkan login user root
sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config

# Lakukan restart layanan SSH untuk menerapkan perubahan
systemctl restart sshd

echo "Konfigurasi SSH telah diubah. Sekarang Anda dapat login menggunakan user root."
